### ISSUE TITLE
Remove Contributors

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Payment-Processor#160]
- [x] Remove Osaro from Design team
- [ ] Remove Mar Nina from Marketing team 
- [x] Remove Ijeoma from Marketing team
- [x] Remove Chibuzor from Marketing team
- [x] Remove Martyn from New User Operation team

**Comment by RajputUsman** [comment]
@kristykjlee Couldn't Find anyone with the name of Mar Nina
