### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by bojan-ilijevski** [thenewboston-developers/Payment-Processor#190]
team: Reddit Moderators
title: Reddit Moderator
isLead: False
display_name: Dushko Manev
github_username: manevdusko
profile_image: https://avatars.githubusercontent.com/u/37742873?v=4
slack_username: Dushko Manev
account_number: 39cf5de525fc20c185b890adc4d4e786b493a5f614e24f3356aabc7662d1ce08

**Comment by RajputUsman** [comment]
Hi @bojan-ilijevski ask Reddit Moderators **Team lead** to open an issue here or DM **Rajput Usman** on Discord/slack.
