### ISSUE TITLE
Add backend-devs

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Payment-Processor#212]
Bucky added 2 new contributors to the weekly report of Backend Devs. 
**Weekly Report:** https://github.com/thenewboston-developers/Activity-Reports/issues/95

**Comment by RajputUsman** [comment]
Kindly ask the Team Lead to open an issue related to New Contributors and fill in the required details required in the [issue](https://github.com/thenewboston-developers/Payment-Processor/issues/new/choose).

**Comment by manishram** [comment]
@angle943 can you please have a look at this one?

**Comment by manishram** [comment]
Closing this issue. 
**Reason:** Change in the Team structure.
