### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Payment-Processor#61]
team: Project Proposal
title: Project Proposals Manager
isLead: true
display_name: Manish Ram 
github_username: manishram
profile_image: https://avatars0.githubusercontent.com/u/22790904?s=400&u=643810e6c9d5686df409132b01863f9e065df6c1&v=4
slack_username: Manish
account_number: 0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by buckyroberts** [comment]
Approved
