### ISSUE TITLE
User mentioned they were not paid last Sunday (11/15/20) 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Payment-Processor#74]
Please check if the user was not paid last Sunday, and if the issue they stated is true or not. If true, please pay them 19,600 **only for last Sunday**

Name: Pulkit Bajaj
Team:  Marketing
Issue: Pulkit mentioned his balance is 0
Account Number: c8339f9aa70d6c90db9c3e52ada23311643ad433221b14b9b0248b6dd94b3f47

**Comment by odetolataiwo** [comment]
@kristykjlee he hasn't been added to the teams. I need further details to create an issue for him.

**Comment by kristykjlee** [comment]
> @kristykjlee he hasn't been added to the teams. I need further details to create an issue for him.

Hey @odetolataiwo Pulkit is currently on the teams page on our website. He is the Marketing Team Lead. What additional information do you need? https://thenewboston.com/teams

**Comment by odetolataiwo** [comment]
Noted. On it now
