### ISSUE TITLE
Remove Members from Teams page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Payment-Processor#77]
This issue is linked to issue :https://github.com/thenewboston-developers/Website/issues/994

For the members that are listed, please also remove them from weekly payments. 

1. Amy Burcham from Marketing
2. Khairul Akmal from Design
3. Sush from Design

**Comment by odetolataiwo** [comment]
@kristykjlee none of them are listed in the teams file. Closing this issue now.
